package dk.dma.enav.model.ship;

public enum ShipType {
    ANTI_POLLUTION, CARGO, DIVING, DREDGING, FISHING, HSC, LAW_ENFORCEMENT, MEDICAL, MILITARY, PASSENGER, PILOT, PLEASURE, PORT_TENDER, SAILING, SAR, SHIPS_ACCORDING_TO_RR, TANKER, TOWING, TOWING_LONG_WIDE, TUG, UNDEFINED, UNKNOWN, WIG
}
